CREATE TABLE quotas_FR(
   Categorie VARCHAR(23) NOT NULL PRIMARY KEY
  ,Mois      VARCHAR(6) NOT NULL
  ,Segment   VARCHAR(23) NOT NULL
  ,Cible     INTEGER  NOT NULL
);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-14','Entreprise',236);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-14','Entreprise individuelle',2382);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-14','Grand public',2777);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-14','Entreprise',19);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-14','Entreprise individuelle',13);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-14','Grand public',1978);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-14','Entreprise',5002);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-14','Entreprise individuelle',3741);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-14','Grand public',5923);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-14','Entreprise',3218);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-14','Entreprise individuelle',2893);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-14','Grand public',1870);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-14','Entreprise',2843);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-14','Grand public',3454);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-14','Entreprise',2718);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-14','Entreprise individuelle',2413);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-14','Grand public',7910);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-14','Entreprise',5840);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-14','Entreprise individuelle',2272);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-14','Grand public',2223);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-14','Entreprise',3210);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-14','Entreprise individuelle',48);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-14','Grand public',3609);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-14','Entreprise',2712);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-14','Entreprise individuelle',4577);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-14','Grand public',15906);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-14','Entreprise',4719);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-14','Entreprise individuelle',435);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-14','Grand public',7059);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-14','Entreprise',5871);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-14','Entreprise individuelle',1554);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-14','Grand public',13152);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-14','Entreprise',7760);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-14','Entreprise individuelle',5228);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-14','Grand public',16162);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-15','Entreprise',644);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-15','Entreprise individuelle',321);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-15','Grand public',10030);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-15','Entreprise',963);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-15','Grand public',2214);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-15','Entreprise',5187);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-15','Entreprise individuelle',3483);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-15','Grand public',3795);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-15','Entreprise',1845);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-15','Entreprise individuelle',1274);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-15','Grand public',6971);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-15','Entreprise',1808);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-15','Entreprise individuelle',896);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-15','Grand public',6517);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-15','Entreprise',4497);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-15','Entreprise individuelle',916);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-15','Grand public',1831);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-15','Entreprise',3930);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-15','Entreprise individuelle',777);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-15','Grand public',9083);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-15','Entreprise',4496);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-15','Entreprise individuelle',2324);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-15','Grand public',2733);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-15','Entreprise',3524);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-15','Entreprise individuelle',3744);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-15','Grand public',17906);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-15','Entreprise',2014);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-15','Entreprise individuelle',1972);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-15','Grand public',8024);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-15','Entreprise',10453);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-15','Entreprise individuelle',4814);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-15','Grand public',14167);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-15','Entreprise',5615);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-15','Entreprise individuelle',7745);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-15','Grand public',8527);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-16','Entreprise',3935);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-16','Entreprise individuelle',355);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-16','Grand public',3234);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-16','Entreprise',697);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-16','Entreprise individuelle',274);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-16','Grand public',2888);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-16','Entreprise',4089);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-16','Entreprise individuelle',1707);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-16','Grand public',6453);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-16','Entreprise',2460);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-16','Entreprise individuelle',3573);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-16','Grand public',7102);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-16','Entreprise',9325);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-16','Entreprise individuelle',1051);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-16','Grand public',4221);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-16','Entreprise',4389);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-16','Entreprise individuelle',1784);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-16','Grand public',6141);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-16','Entreprise',4758);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-16','Entreprise individuelle',326);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-16','Grand public',7993);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-16','Entreprise',7704);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-16','Entreprise individuelle',1523);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-16','Grand public',3833);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-16','Entreprise',9468);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-16','Entreprise individuelle',2506);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-16','Grand public',14011);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-16','Entreprise',4671);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-16','Entreprise individuelle',1256);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-16','Grand public',4139);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-16','Entreprise',12645);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-16','Entreprise individuelle',4273);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-16','Grand public',16946);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-16','Entreprise',11767);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-16','Entreprise individuelle',1919);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-16','Grand public',22624);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-17','Entreprise',2020);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-17','Entreprise individuelle',286);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jan-17','Grand public',3529);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-17','Entreprise',1301);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-17','Entreprise individuelle',3488);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Feb-17','Grand public',2005);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-17','Entreprise',3232);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-17','Entreprise individuelle',661);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Mar-17','Grand public',6810);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-17','Entreprise',3847);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-17','Entreprise individuelle',2131);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Apr-17','Grand public',2647);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-17','Entreprise',5950);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-17','Entreprise individuelle',2142);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','May-17','Grand public',7989);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-17','Entreprise',4588);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-17','Entreprise individuelle',4891);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jun-17','Grand public',7471);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-17','Entreprise',3328);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-17','Entreprise individuelle',1807);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Jul-17','Grand public',8396);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-17','Entreprise',4825);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-17','Entreprise individuelle',1720);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Aug-17','Grand public',7897);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-17','Entreprise',8422);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-17','Entreprise individuelle',5968);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Sep-17','Grand public',14509);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-17','Entreprise',8157);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-17','Entreprise individuelle',4119);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Oct-17','Grand public',8993);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-17','Entreprise',7720);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-17','Entreprise individuelle',10587);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Nov-17','Grand public',13401);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-17','Entreprise',7079);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-17','Entreprise individuelle',5782);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Fournitures de bureau','Dec-17','Grand public',21857);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-14','Entreprise',730);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-14','Entreprise individuelle',1530);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-14','Grand public',2620);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-14','Entreprise',471);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-14','Entreprise individuelle',157);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-14','Grand public',471);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-14','Entreprise',1370);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-14','Entreprise individuelle',2532);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-14','Grand public',4449);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-14','Entreprise',8113);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-14','Entreprise individuelle',677);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-14','Grand public',2760);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-14','Entreprise',3758);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-14','Entreprise individuelle',1750);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-14','Grand public',1520);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-14','Entreprise',1125);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-14','Entreprise individuelle',2078);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-14','Grand public',9478);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-14','Entreprise',1664);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-14','Entreprise individuelle',1027);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-14','Grand public',12387);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-14','Entreprise',2563);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-14','Entreprise individuelle',1397);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-14','Grand public',6994);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-14','Entreprise',5582);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-14','Entreprise individuelle',1462);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-14','Grand public',20160);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-14','Entreprise',3465);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-14','Entreprise individuelle',990);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-14','Grand public',2423);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-14','Entreprise',11723);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-14','Entreprise individuelle',2453);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-14','Grand public',12699);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-14','Entreprise',8154);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-14','Entreprise individuelle',1846);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-14','Grand public',7848);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-15','Entreprise',924);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-15','Entreprise individuelle',184);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-15','Grand public',585);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-15','Entreprise',659);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-15','Entreprise individuelle',118);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-15','Grand public',4294);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-15','Entreprise',4473);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-15','Entreprise individuelle',291);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-15','Grand public',11393);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-15','Entreprise',698);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-15','Entreprise individuelle',5921);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-15','Grand public',5447);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-15','Entreprise',1538);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-15','Entreprise individuelle',1815);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-15','Grand public',5188);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-15','Entreprise',2895);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-15','Entreprise individuelle',900);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-15','Grand public',7050);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-15','Entreprise',1489);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-15','Entreprise individuelle',585);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-15','Grand public',2509);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-15','Entreprise',1753);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-15','Entreprise individuelle',1224);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-15','Grand public',8134);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-15','Entreprise',6281);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-15','Entreprise individuelle',3022);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-15','Grand public',9591);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-15','Entreprise',2411);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-15','Entreprise individuelle',2312);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-15','Grand public',3627);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-15','Entreprise',7361);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-15','Entreprise individuelle',3007);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-15','Grand public',9721);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-15','Entreprise',3361);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-15','Entreprise individuelle',2652);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-15','Grand public',10000);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-16','Entreprise',2472);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-16','Entreprise individuelle',1763);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-16','Grand public',1008);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-16','Entreprise',1275);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-16','Entreprise individuelle',2014);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-16','Grand public',3172);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-16','Entreprise',7127);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-16','Entreprise individuelle',1477);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-16','Grand public',7755);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-16','Entreprise',2607);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-16','Entreprise individuelle',1779);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-16','Grand public',6227);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-16','Entreprise',2577);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-16','Entreprise individuelle',3646);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-16','Grand public',6498);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-16','Entreprise',2561);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-16','Entreprise individuelle',1830);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-16','Grand public',5959);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-16','Entreprise',4374);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-16','Entreprise individuelle',856);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-16','Grand public',7141);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-16','Entreprise',2196);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-16','Entreprise individuelle',1653);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-16','Grand public',5076);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-16','Entreprise',4319);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-16','Entreprise individuelle',9160);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-16','Grand public',9221);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-16','Entreprise',3159);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-16','Entreprise individuelle',8690);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-16','Grand public',2685);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-16','Entreprise',7852);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-16','Entreprise individuelle',3806);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-16','Grand public',8857);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-16','Entreprise',12176);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-16','Entreprise individuelle',6104);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-16','Grand public',20551);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-17','Entreprise',5388);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-17','Entreprise individuelle',2475);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jan-17','Grand public',13593);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-17','Entreprise',3607);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-17','Entreprise individuelle',1220);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Feb-17','Grand public',2122);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-17','Entreprise',4849);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-17','Entreprise individuelle',1917);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Mar-17','Grand public',7462);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-17','Entreprise',5126);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-17','Entreprise individuelle',6013);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Apr-17','Grand public',3866);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-17','Entreprise',5535);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-17','Entreprise individuelle',1817);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','May-17','Grand public',6117);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-17','Entreprise',8239);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-17','Entreprise individuelle',2127);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jun-17','Grand public',4915);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-17','Entreprise',3950);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-17','Entreprise individuelle',1918);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Jul-17','Grand public',4605);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-17','Entreprise',14023);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-17','Entreprise individuelle',2848);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Aug-17','Grand public',12678);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-17','Entreprise',6898);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-17','Entreprise individuelle',4941);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Sep-17','Grand public',19653);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-17','Entreprise',9328);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-17','Entreprise individuelle',5337);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Oct-17','Grand public',8471);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-17','Entreprise',12769);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-17','Entreprise individuelle',4202);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Nov-17','Grand public',11806);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-17','Entreprise',10698);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-17','Entreprise individuelle',3789);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Mobilier','Dec-17','Grand public',16405);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-14','Entreprise',595);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-14','Entreprise individuelle',1411);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-14','Grand public',1033);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-14','Entreprise',697);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-14','Grand public',923);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-14','Entreprise',4392);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-14','Entreprise individuelle',27315);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-14','Grand public',1270);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-14','Entreprise',2882);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-14','Entreprise individuelle',1368);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-14','Grand public',4252);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-14','Entreprise',2196);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-14','Grand public',7108);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-14','Entreprise',248);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-14','Entreprise individuelle',71);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-14','Grand public',8396);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-14','Entreprise',2179);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-14','Entreprise individuelle',300);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-14','Grand public',5136);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-14','Entreprise',1561);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-14','Entreprise individuelle',2794);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-14','Grand public',4907);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-14','Entreprise',7178);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-14','Entreprise individuelle',380);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-14','Grand public',21691);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-14','Entreprise',4248);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-14','Entreprise individuelle',1051);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-14','Grand public',6829);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-14','Entreprise',3660);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-14','Entreprise individuelle',6476);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-14','Grand public',18233);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-14','Entreprise',4026);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-14','Entreprise individuelle',4533);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-14','Grand public',11187);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-15','Entreprise',1526);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-15','Grand public',2547);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-15','Entreprise',1072);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-15','Grand public',2251);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-15','Entreprise',6477);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-15','Entreprise individuelle',1130);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-15','Grand public',2612);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-15','Entreprise',1492);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-15','Entreprise individuelle',59);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-15','Grand public',9285);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-15','Entreprise',1830);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-15','Entreprise individuelle',827);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-15','Grand public',8209);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-15','Entreprise',1488);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-15','Entreprise individuelle',587);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-15','Grand public',4023);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-15','Entreprise',1611);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-15','Entreprise individuelle',305);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-15','Grand public',8089);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-15','Entreprise',5224);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-15','Entreprise individuelle',1316);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-15','Grand public',8510);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-15','Entreprise',6909);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-15','Entreprise individuelle',1949);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-15','Grand public',10372);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-15','Entreprise',3685);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-15','Entreprise individuelle',1217);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-15','Grand public',4989);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-15','Entreprise',9050);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-15','Entreprise individuelle',6917);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-15','Grand public',7787);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-15','Entreprise',6764);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-15','Entreprise individuelle',7516);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-15','Grand public',19981);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-16','Entreprise',3007);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-16','Entreprise individuelle',960);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-16','Grand public',1488);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-16','Entreprise',876);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-16','Entreprise individuelle',1523);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-16','Grand public',10556);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-16','Entreprise',2323);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-16','Entreprise individuelle',9211);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-16','Grand public',8484);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-16','Entreprise',11057);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-16','Entreprise individuelle',3068);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-16','Grand public',1367);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-16','Entreprise',6475);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-16','Entreprise individuelle',1622);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-16','Grand public',19512);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-16','Entreprise',747);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-16','Entreprise individuelle',4784);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-16','Grand public',9821);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-16','Entreprise',2844);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-16','Entreprise individuelle',2371);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-16','Grand public',7077);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-16','Entreprise',3627);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-16','Entreprise individuelle',830);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-16','Grand public',5614);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-16','Entreprise',3652);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-16','Entreprise individuelle',1182);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-16','Grand public',17170);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-16','Entreprise',22270);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-16','Entreprise individuelle',6461);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-16','Grand public',3052);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-16','Entreprise',7890);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-16','Entreprise individuelle',3478);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-16','Grand public',14542);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-16','Entreprise',10807);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-16','Entreprise individuelle',3640);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-16','Grand public',7006);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-17','Entreprise',4522);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-17','Entreprise individuelle',5388);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jan-17','Grand public',6536);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-17','Entreprise',2732);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-17','Entreprise individuelle',1784);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Feb-17','Grand public',1296);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-17','Entreprise',5206);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-17','Entreprise individuelle',3653);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Mar-17','Grand public',20350);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-17','Entreprise',7659);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-17','Entreprise individuelle',5101);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Apr-17','Grand public',3115);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-17','Entreprise',2916);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-17','Entreprise individuelle',4984);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','May-17','Grand public',5943);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-17','Entreprise',5976);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-17','Entreprise individuelle',4111);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jun-17','Grand public',5629);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-17','Entreprise',9746);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-17','Entreprise individuelle',6215);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Jul-17','Grand public',7375);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-17','Entreprise',5991);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-17','Entreprise individuelle',1406);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Aug-17','Grand public',8441);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-17','Entreprise',9506);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-17','Entreprise individuelle',8677);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Sep-17','Grand public',9905);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-17','Entreprise',7391);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-17','Entreprise individuelle',17924);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Oct-17','Grand public',4982);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-17','Entreprise',24033);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-17','Entreprise individuelle',5354);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Nov-17','Grand public',18415);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-17','Entreprise',2420);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-17','Entreprise individuelle',5934);
INSERT INTO quotas_FR(Categorie,Mois,Segment,Cible) VALUES ('Produits technologiques','Dec-17','Grand public',14723);
